"""HTML emitter: IR -> one self-contained file.

Self-contained means exactly that. CSS and JS are inlined, SVG is embedded,
and there is no outbound request of any kind -- not a font, not an icon, not an
analytics beacon. These files get mailed, dropped on SharePoint, and opened on
laptops with restricted network access.

Deterministic: the only date in the output is `docmeta.as_of`, taken from the
IR. Nothing reads the clock, so the golden test can byte-compare.
"""
from __future__ import annotations

from pathlib import Path

from .. import ir as IR
from ..blocks import Ctx, render_block

STANDARD = Path(__file__).resolve().parents[3] / "standard"

LABELS = {
    "ko": {
        "version": "버전", "as_of": "기준일", "org": "대상 조직",
        "author": "작성", "approver": "승인", "next_review": "다음 리뷰",
        "classification": "문서 등급",
        "toc": "목차", "generated": "생성", "ir": "IR 해시",
        "lang_ko": "한국어", "lang_en": "English",
    },
    "en": {
        "version": "Version", "as_of": "As of", "org": "Scope",
        "author": "Author", "approver": "Approver", "next_review": "Next review",
        "classification": "Classification",
        "toc": "Contents", "generated": "Generated by", "ir": "IR hash",
        "lang_ko": "한국어", "lang_en": "English",
    },
}

CONTROL_ORDER = ("version", "as_of", "org", "author", "approver", "next_review", "classification")


def _read(rel: str) -> str:
    return (STANDARD / rel).read_text(encoding="utf-8")


def _head(ir: dict, ctx: Ctx, L: dict) -> str:
    m = ir.get("docmeta") or {}
    sub = (f'<div class="sds-subtitle">{ctx.text(m["subtitle"])}</div>'
           if m.get("subtitle") else "")

    fields = []
    for key in CONTROL_ORDER:
        val = m.get(key)
        if not val:
            continue
        fields.append(f"<div><dt>{L[key]}</dt><dd>{ctx.raw_text(val)}</dd></div>")

    toggle = ""
    if ir.get("bilingual"):
        toggle = (
            '<div style="margin-left:auto;display:flex;gap:6px">'
            f'<button class="sds-btn" data-act="lang" data-lang="ko" aria-pressed="true">'
            f'{L["lang_ko"]}</button>'
            f'<button class="sds-btn" data-act="lang" data-lang="en" aria-pressed="false">'
            f'{L["lang_en"]}</button></div>'
        )

    return (
        f'<header><h1 class="sds-doctitle">{ctx.text(m.get("title"))}</h1>{sub}'
        f'<dl class="sds-control">{"".join(fields)}{toggle}</dl></header>'
    )


def _toc(ir: dict, ctx: Ctx, L: dict) -> str:
    sections = ir.get("sections") or []
    if len(sections) < 4:
        return ""
    items = []
    for i, s in enumerate(sections, start=1):
        tag = ('<span class="sds-derived-tag">derived</span>'
               if s.get("derived") else "")
        items.append(
            f'<li><span class="n">{i}</span>'
            f'<a href="#{ctx.attr(s.get("id"))}">{ctx.text(s.get("title"))}</a>{tag}</li>'
        )
    return (f'<nav class="sds-toc" aria-label="{L["toc"]}">'
            f'<ol>{"".join(items)}</ol></nav>')


def _sections(ir: dict, ctx: Ctx) -> str:
    out = []
    for i, s in enumerate(ir.get("sections") or [], start=1):
        tag = ('<span class="sds-derived-tag">derived</span>'
               if s.get("derived") else "")
        title_en = s.get("title_en")
        title = ctx.text(s.get("title"))
        if title_en:
            title = (f'<span class="sds-ko">{title}</span>'
                     f'<span class="sds-en">{ctx.text(title_en)}</span>')
        out.append(f'<section class="sds-section" id="{ctx.attr(s.get("id"))}">'
                   f'<h2><span class="n">{i}</span>{title}{tag}</h2>')
        if s.get("intro"):
            out.append(f'<div class="sds-intro">{ctx.text(s["intro"])}</div>')
        for b in s.get("blocks") or []:
            out.append(f'<div class="sds-block">{render_block(b, ctx)}</div>')
        out.append("</section>")
    return "".join(out)


def _foot(ir: dict, ctx: Ctx, L: dict, sha: str) -> str:
    m = ir.get("docmeta") or {}
    bits = [
        f'<span>{L["generated"]} <code>somdoc {IR.ENGINE_VERSION}</code></span>',
        f'<span>{L["as_of"]} <code>{ctx.raw_text(m.get("as_of"))}</code></span>',
        f'<span>{L["ir"]} <code>{sha[:12]}</code></span>',
    ]
    if ir.get("doc_type"):
        bits.append(f'<span>doc_type <code>{ctx.raw_text(ir["doc_type"])}</code></span>')
    return f'<footer class="sds-foot">{"".join(bits)}</footer>'


def emit(ir: dict, *, embed_fonts: bool = False) -> str:
    IR.assert_valid(ir)

    lang = ir.get("lang") or "ko"
    L = LABELS.get(lang, LABELS["ko"])
    ctx = Ctx(metrics=ir.get("metrics") or {}, lang=lang)
    sha = IR.ir_sha256(ir)
    m = ir.get("docmeta") or {}

    style = _read("themes/tokens.css") + "\n" + _read("themes/sds-base.css")
    if embed_fonts:
        extra = STANDARD / "themes" / "fonts.embedded.css"
        if extra.exists():
            style = extra.read_text(encoding="utf-8") + "\n" + style
        else:
            raise IR.IRError(
                "--embed-fonts was requested but standard/themes/fonts.embedded.css "
                "does not exist. Generate it first, or drop the flag and rely on the "
                "local font fallback stack."
            )

    body = _head(ir, ctx, L) + _toc(ir, ctx, L) + _sections(ir, ctx)

    out = _read("shell/doc.shell.html")
    for token, value in (
        ("{{LANG}}", lang),
        ("{{THEME}}", ir.get("theme") or "paper"),
        ("{{TITLE}}", ctx.raw_text(m.get("title"))),
        ("{{ENGINE_VERSION}}", IR.ENGINE_VERSION),
        ("{{IR_SHA256}}", sha),
        ("{{AS_OF}}", ctx.raw_text(m.get("as_of"))),
        ("{{STYLE}}", style),
        ("{{BODY}}", body),
        ("{{FOOT}}", _foot(ir, ctx, L, sha)),
        ("{{SCRIPT}}", _read("shell/sds.js")),
    ):
        out = out.replace(token, value)

    leftover = [t for t in ("{{STYLE}}", "{{BODY}}", "{{SCRIPT}}", "{{TITLE}}") if t in out]
    if leftover:
        raise IR.IRError(f"shell placeholders left unfilled: {leftover}")
    return out
